### ISSUE TITLE
Incorrect existing likely subtags

### ISSUE THREAD

**Issue by raphlinus** [projectfluent/fluent-locale-rs#10]
This issue is related to #9, and I want to try to figure it out while making a PR.

First, there are two locales for which the existing logic is simply wrong. "cs" results in "cs-CS", while the region should be CZ, and similarly for "sr", should be "sr-Cyrl-RS" rather than "sr-Cyrl-SR".

A deeper issue is that this logic is very inconsistent whether it adds a script or not. It feels to me like the right thing to do is add a script. However, this makes three of the negotiate tests fail. I feel that if any downstream logic is dependent on the script not being present (as is the case now), it is pretty fragile. However, fixing this feels like a bit of a yak-shave, so I'm filing this issue asking for advice.

I'll also prepare a minimally invasive PR for likely subtags.

**Comment by raphlinus** [comment]
On a little deeper investigation, I think the script tags were a red herring. It might have something to do with the CLDR mapping "und" to "en-Latn-US", but I'm not sure about that. What I'm going to do is PR something that has a test failure when the "likely-subtags" feature is set, and hopefully we can sort it out as part of the review of the PR.

**Comment by zbraniecki** [comment]
I'll close this issue since we now have it filed in `unic-locale` crate.
