### ISSUE TITLE
Re-export `unic_langid::{LanguageIdentifier, LanguageIdentifierError}`

### ISSUE THREAD

**Issue by mamekoro** [projectfluent/fluent-locale-rs#24]
Please re-export `unic_langid::{LanguageIdentifier, LanguageIdentifierError}` as they are included in the public API.

**Comment by zbraniecki** [comment]
Done in https://github.com/projectfluent/fluent-langneg-rs/commit/40957e71d64d5db31c0575dce7c55fdef12b3c6b
