### ISSUE TITLE
copyright holder missing in LICENSE file

### ISSUE THREAD

**Issue by tenzap** [projectfluent/fluent-locale-rs#25]
License file didn't set the copyright holder. It currently has a placeholder value:
```
   Copyright {yyyy} {name of copyright owner}
```
https://github.com/projectfluent/fluent-langneg-rs/blob/master/LICENSE#L189C4-L189C46

Could you please fix that and release a version with that fix included?

**Comment by zbraniecki** [comment]
Thank you, fixed in https://github.com/projectfluent/fluent-langneg-rs/commit/a0fb0390a5bcbd43718cc9279ff2c0fbc390a9af
