### ISSUE TITLE
Likely subtags

### ISSUE THREAD

**Issue by raphlinus** [projectfluent/fluent-locale-rs#9]
I need "likely subtags" for script-aware fallback. ICU has [an implementation](http://icu-project.org/apiref/icu4c64rc/classicu_1_1Locale.html#a974d212572d7fc61a0579f820100a8f6).

I actually have this pretty well implemented. The question is whether it belongs in fluent-locale-rs or whether it should be in skribo. I estimate that it's in the ballpark of 50k of code and data; I could probably get it down a little.

Also, I haven't implemented the deprecated subtags (for example, the conversion of "sh" to "sr_Latn". I suspect I won't miss them for text rendering, but other applications might want them (for example, so that hyphenation can handle "no-NO"). If I submitted a PR, would you want these?

A "no" answer is fine - it'll just live in skribo.

**Comment by zbraniecki** [comment]
Hmm, that's a good question.

We have a poors man version of it - https://github.com/projectfluent/fluent-locale-rs/blob/master/src/negotiate/likely_subtags.rs
Are you talking about including the whole algorithm here? We could make it an optional build flag to include the whole set.

Eventually, I believe this should be part of UNIC.

**Comment by raphlinus** [comment]
Oh for some reason I missed the version in negotiate. My implementation is more or less the whole algorithm, with data from CLDR, with the exception of the deprecated and grandfathered tags. I'm quite fine putting it under a feature if there's concern about the data size.

**Comment by zbraniecki** [comment]
I'm going to close this issue here since we now track it in `unic-locale` crate.
